use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=config/ip_ranges.json");

    let json_path = Path::new("config/ip_ranges.json");
    let json_content = fs::read_to_string(json_path).expect("failed to read config/ip_ranges.json");

    let data: serde_json::Value =
        serde_json::from_str(&json_content).expect("failed to parse ip_ranges.json");

    let tiers = data["tiers"].as_object().expect("tiers must be an object");

    let mut output = String::new();
    output.push_str("// @generated by build.rs from config/ip_ranges.json\n");
    output.push_str("// DO NOT EDIT MANUALLY. Edit config/ip_ranges.json and rebuild.\n\n");

    for (tier_name, tier_data) in tiers {
        let entries = tier_data["entries"]
            .as_array()
            .expect("entries must be an array");
        let const_name = tier_to_const_name(tier_name);
        let description = tier_data["description"]
            .as_str()
            .unwrap_or("Generated deny list");

        let _ = writeln!(output, "/// {description}");
        let _ = writeln!(output, "pub const {const_name}: &[&str] = &[");
        for entry in entries {
            let cidr = entry["cidr"].as_str().expect("cidr must be a string");
            let name = entry["name"].as_str().unwrap_or("");
            let rfc = entry["rfc"].as_str().unwrap_or("N/A");
            let _ = writeln!(output, "    \"{cidr}\", // {name} ({rfc})");
        }
        output.push_str("];\n\n");
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("ip_ranges_generated.rs");
    fs::write(&dest_path, output).expect("failed to write generated ip_ranges");
}

fn tier_to_const_name(tier: &str) -> String {
    match tier {
        "iana_ipv4" => "IANA_IPV4_DENY".to_string(),
        "iana_ipv6" => "IANA_IPV6_DENY".to_string(),
        "override" => "OVERRIDE_DENY".to_string(),
        "csp_metadata" => "CSP_METADATA_DENY".to_string(),
        other => other.to_uppercase(),
    }
}
