"""Type stubs for the native ressrf._core extension module."""

from typing import Callable

class RessrfBlockedError(Exception):
    """Raised when a request is blocked by the SSRF policy."""

    ...

class CorePolicyBuilder:
    """Builder for constructing an immutable CorePolicy."""

    def __init__(self, preset: str = "external_only") -> None: ...
    def add_denied(self, cidrs: list[str]) -> None: ...
    def add_allowed(self, cidrs: list[str]) -> None: ...
    def header_rules(
        self,
        required: list[str] | None = None,
        denied: list[str] | None = None,
        auto_xff: bool = False,
    ) -> None: ...
    def protocol_rules(
        self,
        allow_plaintext_http: bool = False,
        require_https: bool = True,
    ) -> None: ...
    def with_cloud(self, name: str) -> None: ...
    def audit_sink(self, callback: Callable[[str], None]) -> None: ...
    def build(self) -> CorePolicy: ...

class CorePolicy:
    """Immutable SSRF policy backed by the Rust core."""

    def is_network_allowed(self, ips: list[str]) -> None: ...
    def validate_url(self, url: str) -> None: ...
    def preset(self) -> str: ...

class CoreUriValidator:
    """URI validator for string-only checks (no DNS, no connections)."""

    def __init__(self) -> None: ...
    def add_trusted_suffixes(self, suffixes: list[str]) -> None: ...
    def add_denied_suffixes(self, suffixes: list[str]) -> None: ...
    def with_cloud_provider(self, name: str) -> None: ...
    def validate_url(self, url: str, policy: CorePolicy | None = None) -> None: ...
    def is_trusted_domain(self, domain: str) -> bool: ...

def parse_cidr(cidr_str: str) -> dict[str, object]: ...
def cidr_contains(cidr_str: str, ip_str: str) -> bool: ...
def deny_reason_to_dict(json_str: str) -> dict[str, object]: ...
