// Code generated by ./internal/cmd/gen-data — DO NOT EDIT.
// Source: crates/ressrf-core/config/domains_*.json
// last_updated: 2026-05-09

package engine

// cloudConfigs is built from crates/ressrf-core/config/domains_*.json.
// To refresh, run: go generate ./...
var cloudConfigs = map[CloudProvider]cloudConfig{
	CloudAWS: {
		denyRanges: []string{
			"169.254.169.254/32", // IMDS (IPv4)
			"fd00:ec2::254/128",  // IMDSv2 (IPv6)
			"169.254.170.2/32",   // ECS task metadata
		},
		deniedSuffixes: []string{
			".compute.internal",
			".ec2.internal",
			".internal",
		},
		serviceSuffixes: []string{
			".amazonaws.com",
		},
		tier: TierCloudAws,
	},
	CloudAzure: {
		denyRanges: []string{
			"169.254.169.254/32", // IMDS
			"168.63.129.16/32",   // Wireserver / DHCP
		},
		deniedSuffixes: []string{
			".internal.cloudapp.net",
		},
		serviceSuffixes: []string{
			".azurecr.io",
			".core.chinacloudapi.cn",
			".core.cloudapi.de",
			".core.usgovcloudapi.net",
			".core.windows.net",
			".database.windows.net",
			".documents.azure.com",
			".servicebus.windows.net",
			".vault.azure.cn",
			".vault.azure.net",
		},
		tier: TierCloudAzure,
	},
	CloudGCP: {
		denyRanges: []string{
			"169.254.169.254/32", // GCP metadata server
		},
		deniedSuffixes: []string{
			".internal",
			"metadata.google.internal",
		},
		serviceSuffixes: []string{
			".appspot.com",
			".googleapis.com",
			".run.app",
		},
		tier: TierCloudGcp,
	},
}
