// Code generated by ./internal/cmd/gen-data — DO NOT EDIT.
// Source: crates/ressrf-core/config/ip_ranges.json
// last_updated: 2026-05-09

package engine

// ianaIPv4Deny: IANA IPv4 special-purpose ranges (Globally Reachable = False) plus infrastructure-only (Tier 1b)
var ianaIPv4Deny = [...]CIDR{
	mustParseCIDR("0.0.0.0/8", TierIANA),          // This network (RFC791)
	mustParseCIDR("10.0.0.0/8", TierIANA),         // Private-Use (RFC1918)
	mustParseCIDR("100.64.0.0/10", TierIANA),      // Shared Address Space (RFC6598)
	mustParseCIDR("127.0.0.0/8", TierIANA),        // Loopback (RFC1122)
	mustParseCIDR("169.254.0.0/16", TierIANA),     // Link Local (RFC3927)
	mustParseCIDR("172.16.0.0/12", TierIANA),      // Private-Use (RFC1918)
	mustParseCIDR("192.0.0.0/24", TierIANA),       // IETF Protocol Assignments (RFC6890)
	mustParseCIDR("192.0.0.0/29", TierIANA),       // IPv4 Service Continuity Prefix (RFC7335)
	mustParseCIDR("192.0.0.8/32", TierIANA),       // IPv4 dummy address (RFC7600)
	mustParseCIDR("192.0.0.170/32", TierIANA),     // NAT64/DNS64 Discovery (RFC8880)
	mustParseCIDR("192.0.2.0/24", TierIANA),       // Documentation (TEST-NET-1) (RFC5737)
	mustParseCIDR("192.31.196.0/24", TierIANA),    // AS112-v4 [Tier 1b] (RFC7535)
	mustParseCIDR("192.52.193.0/24", TierIANA),    // AMT [Tier 1b] (RFC7450)
	mustParseCIDR("192.88.99.0/24", TierIANA),     // Deprecated (6to4 Relay Anycast) [Tier 1b] (RFC7526)
	mustParseCIDR("192.88.99.2/32", TierIANA),     // 6a44-relay anycast address (RFC6751)
	mustParseCIDR("192.168.0.0/16", TierIANA),     // Private-Use (RFC1918)
	mustParseCIDR("192.175.48.0/24", TierIANA),    // Direct Delegation AS112 Service [Tier 1b] (RFC7534)
	mustParseCIDR("198.18.0.0/15", TierIANA),      // Benchmarking (RFC2544)
	mustParseCIDR("198.51.100.0/24", TierIANA),    // Documentation (TEST-NET-2) (RFC5737)
	mustParseCIDR("203.0.113.0/24", TierIANA),     // Documentation (TEST-NET-3) (RFC5737)
	mustParseCIDR("224.0.0.0/4", TierIANA),        // Multicast (RFC5771)
	mustParseCIDR("240.0.0.0/4", TierIANA),        // Reserved (RFC1112)
	mustParseCIDR("255.255.255.255/32", TierIANA), // Limited Broadcast (RFC919)
}

// ianaIPv6Deny: IANA IPv6 special-purpose ranges (Globally Reachable = False)
var ianaIPv6Deny = [...]CIDR{
	mustParseCIDR("::1/128", TierIANA),        // Loopback Address (RFC4291)
	mustParseCIDR("::/128", TierIANA),         // Unspecified Address (RFC4291)
	mustParseCIDR("64:ff9b:1::/48", TierIANA), // IPv4-IPv6 Translat. (RFC8215)
	mustParseCIDR("100::/64", TierIANA),       // Discard-Only Address Block (RFC6666)
	mustParseCIDR("100:0:0:1::/64", TierIANA), // Dummy IPv6 Prefix (RFC9780)
	mustParseCIDR("2001:2::/48", TierIANA),    // Benchmarking (RFC5180)
	mustParseCIDR("2001:3::/32", TierIANA),    // AMT [Tier 1b] (RFC7450)
	mustParseCIDR("2001:db8::/32", TierIANA),  // Documentation (RFC3849)
	mustParseCIDR("3fff::/20", TierIANA),      // Documentation (RFC9637)
	mustParseCIDR("5f00::/16", TierIANA),      // Segment Routing (SRv6) SIDs (RFC9602)
	mustParseCIDR("fc00::/7", TierIANA),       // Unique-Local (RFC4193)
	mustParseCIDR("fe80::/10", TierIANA),      // Link-Local Unicast (RFC4291)
	mustParseCIDR("ff00::/8", TierIANA),       // Multicast (RFC4291)
}

// overrideDeny: Tier 1c: ranges wrapping attacker-controlled IPv4 inside IPv6 (6to4, Teredo, NAT64)
var overrideDeny = [...]CIDR{
	mustParseCIDR("2002::/16", TierOverride),    // 6to4 (wraps arbitrary IPv4) (RFC3056)
	mustParseCIDR("2001::/32", TierOverride),    // Teredo (wraps arbitrary IPv4) (RFC4380)
	mustParseCIDR("64:ff9b::/96", TierOverride), // NAT64 well-known prefix (RFC6052)
}

// cspMetadataDeny: Tier 2: Cloud provider metadata endpoints
var cspMetadataDeny = [...]CIDR{
	mustParseCIDR("169.254.169.254/32", TierCSPMetadata), // AWS/Azure/GCP IMDS (N/A)
	mustParseCIDR("169.254.170.2/32", TierCSPMetadata),   // AWS ECS task metadata (N/A)
	mustParseCIDR("168.63.129.16/32", TierCSPMetadata),   // Azure Wireserver / DHCP (N/A)
	mustParseCIDR("fd00:ec2::254/128", TierCSPMetadata),  // AWS IMDSv2 IPv6 (N/A)
}
